- window.js
> fix: opening apps from dash should tile immediately

- README.md
- TESTS.md
- metadata.json
- schemas/org.gnome.shell.extensions.forge.gschema.xml
- tree.js
- window.js
- Added more region targets to drag and drop tiling
- Removed toggling stacked or tabbed layout on the root monitor workspace node
- Tree move API improvements
- Updated tree cleanup iteration of dangling nodes
> Feat dragdrop regions

- Makefile
- tree.js
- window.js
> Fix close window crash

- README.md
- keybindings.js
- schemas/org.gnome.shell.extensions.forge.gschema.xml
- tree.js
- window.js
> feat: swap last active

- window.js
> Fix toggle tiling tabs

- window.js
> When grab operation, do not update the decoration

- schemas/org.gnome.shell.extensions.forge.gschema.xml
- tree.js
- window.js
> feat: enable follow focus

- Makefile
- README.md
- config/windows.json
- keybindings.js
- metadata.json
- settings.js
- tree.js
- window.js
Fixes #90
Fixes #3
Fixes #15 
Fixes #121
> Floating windows

- tree.js
- window.js
Fixes #135
Fixes #137 
Fixes #138
> Mouse open fix + Reset window fix

- window.js
> Fix drag and drop regression

- metadata.json
> Add GNOME 43 to versions

- messages.js
- po/es.po
- po/nl.po
- prefs.js
- schemas/org.gnome.shell.extensions.forge.gschema.xml
- tree.js
- window.js
Closes #152
Closes #67 
Closes #94
> Process floats, border and decoration priority

- window.js
> Removed centering floats automatically for now

- README.md
- messages.js
- po/es.po
- po/nl.po
- prefs.js
- schemas/org.gnome.shell.extensions.forge.gschema.xml
- window.js
> Implement quarter tiling

- README.md
- keybindings.js
- schemas/org.gnome.shell.extensions.forge.gschema.xml
- tree.js
- window.js
Closes #180
Implemented toggling the tab decoration show/hide
> Hide tabs using kbd

- po/pt-br.po
Thanks for this wonderful extension.
> Added translation for Portuguese of Brasil

- po/fr.po
This is actually my first attempt at translation. Even though I'm fluent in both, there may be some awkward choices of words - in the end, I went with the ones I thought were the most suitable
> Add French localization

- window.js
> Remove raise/queue updates when float

- window.js
> Redirect grab op to handler

- tree.js
- window.js
> Implement gaps check per monitor

- preferences/about.js
> fix: bug when opening about window

- indicator.js
- preferences/settings.js
- schemas/org.gnome.shell.extensions.forge.gschema.xml
Closes #231 
[Screencast from 2023-05-31 21-51-18.webm](https://github.com/forge-ext/forge/assets/348125/c9b96fa6-5dad-4ace-8518-acde431560f1)
> Make quick-settings optional

- tree.js
> Ignore DING extension

- indicator.js
> Read indicator values on create

- extension.js
- metadata.json
> Fixes lock screen reset windows

- config/windows.json
> Add Firefox PIP/About to float

- lib/extension/indicator.js
- lib/prefs/settings.js
- po/pt_BR.po
- Added an option to toggle moving the pointer with focus in the tiling menu
- Updated pt_BR translation
> Feature: set move-pointer-focus in the tiling menu

- lib/extension/tree.js
- lib/extension/window.js
- lib/prefs/settings.js
- metadata.json
Minor fixes to get the package compiling in Gnome 46. Tested on Rawhide 46.alpha
> Building for Gnome 46

- lib/extension/window.js
Fix #343
---
Btw, when do you think we can release a new version ?
> Fix moving pointer with the option disabled

- lib/prefs/settings.js
- schemas/org.gnome.shell.extensions.forge.gschema.xml
Makes the changes as suggested by what I said in #371
> Disable Move Pointer with the Focus by default

- po/fr.po
> French translations added 

- po/es.po
> Add spanish translation

- metadata.json
just a metadata change, seems to work
> bump gnome version (48)

- config/windows.json
- Added entry in config/windows.json for evolution, variety, and update manager as float overrides
- Shouldn't affect functionality
- Apps present in Debian/Ubuntu
> Add evolution, variety and update manager as float overrides

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- README.md
I figured it out! One commit for all of my changes :)
Minor edits for readability and clarity for the Bug Report, Feature Request, and README
> Edit Issue formats, touch up README

- po/tr.po
- Add complete Turkish translation for Forge GNOME extension
- Translated all UI strings, settings, and keyboard shortcuts
- Used appropriate Turkish terminology for window management
- Includes proper translator credits and metadata
- Follows GNOME Turkish localization standards
Translator: Mucahit Sahin <mucahitsahin786@gmail.com>
> Add Turkish (tr) translation
