forge-ext/forge

window.js

Dash to Panel on GNOME 40 seems to trigger workareas-changed signal,
causing the entire tree to reload and remove the edited arrangements.
Check for that going to/from overview, ignore reload.
Fixes #80

fix: check overview condition

---

extension.js

The same session flag when user locks screen skips the reloading of the custom stylesheet. Gnome-shell always reloads the default stylesheet.css from any active extension's install dir.
Fixes #86

fix: same session skips reloading the css

---

messages.js
prefs.js
schemas/org.gnome.shell.extensions.forge.gschema.xml

Hello,
I found that there is already a settings key for the default drag-and-drop center layout and the code already considers having this as a variable so I only had to add the settings page views. This commit leaves the Home page as it is and adds a new General settings page, as I was not sure in which other category such option fits (something like "Behavior" would work too).
This is my first time working on something like this so I would appreciate any feedback! I mostly copied code from other similar parts of the extension.
#101

feat: option to choose default dnd layout (introduces appearance layout page)

---

window.js

Fixes #143 - Handle checking the target windows using the monitor node children versus the tree.

Fix drag/drop monitor windows

---

prefs.js
stylesheet.css

Remove hints on non-tiling components

---

tree.js

With Ubuntu 22.10's gnome-shell (43.1) and the current version on extensions.gnome.org (version 61?)...
I've been seeing some oddities when unlocking after leaving it locked for a "little while".  I _think_ it's because X is bouncing the DisplayPort display...?
```
gnome-shell[2846]: meta_monitor_manager_get_logical_monitor_from_number: assertion '(unsigned int) number < g_list_length (manager->logical_monitors)' failed
gnome-shell[2846]: meta_workspace_get_work_area_for_monitor: assertion 'logical_monitor != NULL' failed
...
gnome-shell[2846]: *** BUG ***
gnome-shell[2846]: In pixman_region32_init_rect: Invalid rectangle passed
gnome-shell[2846]: Set a breakpoint on '_pixman_log_error' to debug
```
After some judicious littering of Logger calls, I noticed that the padding computation was …

Add window rect check

---

window.js

Fixes #182.
After a few days of testing, the change seems stable.  Or at least, nothing outwardly visible has gone worse.
Leaving the change at the "most minimal" to keep the change halo as tight as possible, just in case.
Note that this fix also fixes these specific gnome-shell assertions that were happening:
```
gnome-shell[3147]: meta_monitor_manager_get_logical_monitor_from_number: assertion '(unsigned int) number < g_list_length (manager->logical_monitors)' failed
gnome-shell[3147]: meta_workspace_get_work_area_for_monitor: assertion 'logical_monitor != NULL' failed
```

Ignore workareas-changed event with no monitor

---

utils.js
window.js

Fixes #201 - added new grab op bit to recognize moving grab mode.

Add moving unconstrained bit to moving grab-mode

---

window.js

probably not the smallest repro, but it's what I got...
> 1. create 3 windows, so you have 3 columns.
> It ends up looking like:
> ```
> *--> WORKSPACE#1 @ws1
> |   *--> MONITOR#0
> |   |   *--> CON#0
> |   |   |   *--> WINDOW#0
> |   |   *--> CON#1
> |   |   |   *--> WINDOW#0
> |   |   *--> WINDOW#2
> ```
> 
> 2. apply focus on "the leftmost window"
> 
> 3. open up a window that is "already focused" (e.g. Zoom)
> ```
> *--> WORKSPACE#1 @ws1
> |   *--> MONITOR#0
> |   |   *--> CON#0
> |   |   |   *--> WINDOW#0 ... rect:...
> |   |   |   *--> WINDOW#1
> |   |   *--> CON#1
> |   |   |   *--> WINDOW#0
> |   |   *--> WINDOW#2
> ```
> 
> 4. adjust the width of the zoom window.
In my tests, CON#0  would adjust in width. Sometimes it'd push the rightmost window off the right side of the screen. …

Don't resize other windows when resizing floats

---

README.md
config/windows.json
keybindings.js
schemas/org.gnome.shell.extensions.forge.gschema.xml
window.js

Fixes #111 
- Initial rough implementation. It works on Tiled and Floating windows
- Redraw issue when long pressing keybindings - moves the window the wrong way, so user has to press in intervals. Will need to figure out queuing events properly.
- This is a separate implementation from the GNOME built in resize, usually bound at Alt + F8

Resize enhancement

---

messages.js
po/es.po
po/fr.po
po/nl.po
po/pt-br.po
prefs.js
schemas/org.gnome.shell.extensions.forge.gschema.xml

Makes focus hint the default, as in https://github.com/forge-ext/forge/issues/168

Make focus hint default

---

indicator.js
preferences/about.js
utils.js

Fixes #235 
Background: GNOME introduced quick settings in Gnome 43 and following their guide some features are not available in between 43 and 44: https://gjs.guide/extensions/topics/quick-settings.html
I added an issue in GJS Docs if they can put a warning for anyone who stumbles upon it in their examples and find that it is missing in GNOME 43.
https://gitlab.gnome.org/ewlsh/gjs-guide/-/issues/64

Fix quick settings implementation on GNOME 43-44

---

preferences/keyboard.js

When the shortcut entry value is empty, unset the mapping. Keyboard bindings will be further enhanced on #234 perhaps including to disable the Forge's mapping entirely.

Fix keyboard unset

---

preferences/settings.js

When full-screen gaps are disabled, this creates an (IMO) ugly looking yellow border on the right-hand side:
`split-border-toggle` is already a setting that is registered in the gschema.   It is always `true`, since there is not a way to change this setting.  
This change exposes split-border-toggle as a user-configurable setting.  It will allow users to remove the yellow split border on full-screen windows:

Expose split-border-toggle as a configurable setting

---

Makefile
lib/prefs/settings.js
lib/prefs/widgets.js
lib/shared/logger.js

It's not clear why the type information isn't gathered from the schema, but since it's not, we can pass a type hint to the dropdown row constructor.
Fixes #251

fix(prefs): dnd-center-layout dropdown

---

extension.js
lib/extension/utils.js
lib/prefs/appearance.js
lib/prefs/keyboard.js
lib/prefs/settings.js
lib/prefs/widgets.js
prefs.js

forge-ext's extension, "Forge", version 74 has a new review:
JustPerfection posted a review on September 18, 2023:
1. Please remove the version from imports,
because parent is the owner of prefs window and already specified the version:
- line 20-21 prefs.js
- line 4 lib/prefs/keyboard.js
- line 4 lib/prefs/appearance.js
- line 5-6 lib/prefs/widgets.js
- line 3 lib/prefs/settings.js
2. Typo :p in
- line 30 prefs.js (class name)
- line 199 lib/extension/utils.js `orientaton`
3. You need to create objects on enable and null them out in disable (line 34 and 36 extension.js).
Garbage collector cannot do it&#x27;s job otherwise.
4. Selective disable is not allowed (line 69 extension.js):
https://gjs.guide/extensions/review-guidelines/review-guidelines.html#session-modes
Please use the review …

Fix: extensions review feedback

---

lib/extension/window.js

If the title filter starts with a `!`, then every window that does not contain the title match the filter.
This can be useful in cases like Firefox where the main window contains a string but not the others (cf. #285)

Add not include filter

---

Makefile
TESTS.md
lib/extension/tree.js
lib/extension/window.js
lib/prefs/settings.js

- Reworked #252 as rebase didn't work anymore.
- Mostly the same code, but changed a bit to merge existing code.
Ready to review again.

Feature: move mouse with focus to the last position in window

---

lib/extension/window.js
lib/prefs/settings.js
stylesheet.css

I often find myself in a situation where I have a layout, but want to rearrange windows inside that layout. Currently there's no way to do it quickly with a mouse without ruining the layout. You can only be clicking and using "swap with previous" from keyboard, which is annoying. This PR adds an option to not create stacked/tabbed layout on drag and drop to a window center, and to just swap windows instead. This makes it much easier to rearrange windows inside the layout, and tabbed/stacked layouts are still available via keyboard shortcuts.

DND to center option: don't tab/stack, swaps windows instead

---

po/pt_BR.po

This fixes error during build
```
xgettext --from-code=UTF-8 --output=po/forge.pot --package-name "Forge" ./prefs.js ./extension.js ./lib/**/*.js
msgfmt -c po/pt_BR.po -o po/pt_BR.mo
po/pt_BR.po:263: duplicate message definition...
po/pt_BR.po:260: ...this is the location of the first definition
msgfmt: found 1 fatal error
make: *** [Makefile:51: po/pt_BR.mo] Error 1
```

Remove duplicated message definition in pt_BR translation

---

lib/extension/window.js

This was the cause of ghosts windows with dynamic workspaces: Closing a window in a workspace reduced the number of workspaces above it. Windows in these workspaces considered that there was still another window, and finished tiling with a ghost window.
Error log:
```
JS ERROR: TypeError: metaWindow.get_title is not a function
removeFloatOverride@file:///var/home/user/.local/share/gnome-shell/extensions/forge@jmmaranan.com/lib/extension/window.js:106:30
windowDestroy@file:///var/home/user/.local/share/gnome-shell/extensions/forge@jmmaranan.com/lib/extension/window.js:1623:12
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1555:21
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1523:39
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:84:22 …
```

Fix error 'metaWindow.get_title is not a function'

---

.github/workflows/publish.yml
.github/workflows/testing.yml
.prettierignore
Makefile
config/windows.json
metadata.json
package.json

This PR would add:
1. A Github workflow for testing each PR or push to the main branch
1. Currently it only does source code formatting
3. A Github workflow for releasing for GOE
1. But it could work

Feat: Add CI/CD workflows using github actions

---

lib/extension/utils.js
lib/extension/window.js

fixes #269
- makes it possible to scale windows by the corner
- enables scaling with secondary key and super+middleclick
The diff for `lib/extension/window.js` looks complicated but I really only added a loop.

Fix drag resize

---

.github/workflows/publish.yml

- Followup to #373 
- Adding a referer header in upload step of release workflow
- Test by issuing a release

fix: ci: added referer to GOE post in release workflow

---

lib/extension/tree.js

Currently when the gap is zero, windows below tabs are repositioned slightly downward. This causes the windows to exceed the bottom of the screen and results in [a small gap](https://github.com/forge-ext/forge/issues/391) between the window and tabs. This repositioning is unnecessary, so remove it.
Before and after—note the recovery of the bottom border of the window:

Correct vertical position of tabbed windows

---

lib/extension/tree.js
lib/prefs/settings.js
schemas/org.gnome.shell.extensions.forge.gschema.xml

Attempting the enhancement described in #341

Automatically exit the tabbed layout when only a single tab remains

---

metadata.json

All that is needed is adding 47 to metadata.json

Add Gnome 47 support

---

lib/extension/window.js

Fixes #257
When the window becomes `unmanaged`, it should be safe to hide the borders, which also fixes the visual bug mentioned in #257.

fix: hide border of unmanaged windows

---

lib/extension/window.js
lib/prefs/settings.js
po/es.po
po/fr.po
po/it.po
po/nl.po
po/pt_BR.po
schemas/org.gnome.shell.extensions.forge.gschema.xml

This could have been simply done using gnome-tweaks, but it can be buggy at times (see #258). This custom implementation doesn't run into the issues gnome-tweaks does, but this comes at the cost of efficiency: it gets the position of the pointer every 16 milliseconds and updates the focus. I couldn't find a better way of implementing this.

feat: custom implementation of `Focus on Hover`

---

lib/extension/window.js

As mentioned in this review: https://extensions.gnome.org/review/63403

Remove potentially dangling pointer timer

---

lib/prefs/widgets.js
po/es.po
po/fr.po
po/it.po
po/nl.po
po/pt_BR.po

Adds a button to easily clear a shortcut

Add a clear-shortcut button

---

lib/prefs/settings.js
lib/prefs/widgets.js
po/es.po
po/fr.po
po/it.po
po/nl.po
po/pt_BR.po

Slightly updates some of the preferences rows' styles.

Update preferences UI
